server:
  port: 8200

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: notifications.confirmation@gmail.com
    password: xroceazuyizupjeu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


rabbitmq:
  queue:
    name: notQueue
  exchange:
    name: notTopicExchange
  routing:
    key: notRoutingKey
